version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vKb2Xn!!kM94BR
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
    volumes:
      - task-manager-data:/var/lib/postgresql/data
    networks:
      - task-manager-network

  task-manager:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - task-manager-network

volumes:
  task-manager-data:

networks:
  task-manager-network: